### PR TITLE
[WIP] Add ONNX export

### PR DESCRIPTION
**Pull request by Mika412**
This is mainly working, but I need still to do some quick improvements/changes.

Tasks to do:
- [x] Fix optimization script. For now use:
- [ ] Add trajectory loss comparison

For the model optimization, use:
  `python -m onnxsim model.onnx model_sim.onnx`
   `python -m onnxoptimizer model.onnx model_opt.onnx`

### CODE REVIEW

**Review by NicolayP — APPROVED** [review]

**Comment by NicolayP** [comment]
After pulling and installing the new requirements I get the following error on launch of

```python
python -m onnxsim model.onnx model_sim.onnx
```

```bash
/$HOME/anaconda3/envs/pypose/bin/python: No module named onnxsim
```

found this thread:
https://github.com/daquexian/onnx-simplifier/issues/195
can you confirm the libraries version to make sure they match?


The second instruction seems to work but took ~17min

**Comment by Mika412** [comment]
Yes, it's that one. I've forgotten to add that requirement.
You can use the latest ones for now. I'll update the requirements in the next PR

**Comment by NicolayP** [comment]
I also ran it on our GPU server. It works but I can't seem to be able to run the `io_binding` one on another GPU. I Changed the GPU Id to match the one I use in io_binding.bind_input/output but it fails with the following message:

```bash
RuntimeError: Error in execution: /onnxruntime_src/onnxruntime/core/framework/utils.cc:169 onnxruntime::common::Status onnxruntime::utils::BatchOrCopyMLValue(const onnxruntime::SessionState&, const onnxruntime::MLValueCopyInfo&, const OrtValue&, OrtValue&, onnxruntime::Stream*, std::vector<onnxruntime::IDataTransfer::SrcDstPair>*, std::vector<onnxruntime::IDataTransfer::SparseSrcDstPair>*) allocator != nullptr was false. Failed to find allocator for device Device:[DeviceType:1 MemoryType:0 DeviceId:1]
``` 

Trying to understand what's going on but can't seem to find anything related to the issue, do you have a way of testing or any idea what's going on?

**Comment by Mika412** [comment]
Hmm. Interesting. I was able to replicate the same error when I set the `device_type='cpu'`. I would assume that the model is being loaded on one GPU, while the bound values are on another. Check if `get_device` has the same GPU id, as the inference session and the bound input/output.

**Comment by NicolayP** [comment]
So I set the device number in a variable and use it for the binding input output but I don't see in the API nor the code where to set the `InferenceSession` device?

**Comment by Mika412** [comment]
I haven't tried it myself, but there is a way to set it like this:

```
providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
provider_options = [{
    'device_id': 0}]
sess = rt.InferenceSession(MODEL_PATH)
sess.set_providers(providers, provider_options)
```

**Comment by NicolayP** [comment]
Needed to do it a bit differently as you can't see provider and provider option at the same time apparently but I've pushed the updated version and it's working as intended now (at least we can select the GPU)

**Comment by Mika412** [comment]
Nice!

**Pull request merged**
